### ISSUE TITLE
Mejorar marco de trabajo scrum

### ISSUE THREAD

**Issue by alvaro-avilac** [dgsi-lab-gl6-2324/FOSS#4]
Consultar documento [The Scrum Guide](https://scrumguides.org/docs/scrumguide/v2020/2020-Scrum-Guide-US.pdf#zoom=100) para refinar los elementos de la metodología

**Comment by PedroMena1** [comment]
Mira esta web: https://www.scrum.org/: 
Es la web oficial de Scrum ofrece una gran cantidad de información sobre la metodología, incluyendo guías, artículos...
